name: actionlint
description: actionlint
author: Shunsuke Suzuki
inputs:
  sparse-checkout:
    required: false
    description: |
      sparse checkout
  actionlint_options:
    required: false
    description: |
      actionlint's command line options such as `-ignore`.
runs:
  using: composite
  steps:
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: changes
      with:
        filters: |
          value:
            - .github/workflows/*.yml
            - .github/workflows/*.yaml
    - if: steps.changes.outputs.value == 'true'
      uses: suzuki-shunsuke/actionlint-action-main@c8638a5bc72fca0ef2a1a5219896c28fc17986b3 # v0.0.7
      with:
        sparse-checkout: ${{inputs.sparse-checkout}}
        actionlint_options: ${{inputs.actionlint_options}}
      env:
        AQUA_LOG_COLOR: always
