name: actionlint
description: actionlint
author: Shunsuke Suzuki
inputs:
  sparse-checkout:
    required: false
    description: |
      sparse checkout
  actionlint_options:
    required: false
    description: |
      actionlint's command line options such as `-ignore`.
runs:
  using: composite
  steps:
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        filters: |
          value:
            - .github/workflows/*.yml
            - .github/workflows/*.yaml
    - if: steps.changes.outputs.value == 'true'
      uses: suzuki-shunsuke/actionlint-action-main@3ecc526e34555c7a19abe45b4e248816f301228f # v0.0.6
      with:
        sparse-checkout: ${{inputs.sparse-checkout}}
        actionlint_options: ${{inputs.actionlint_options}}
      env:
        AQUA_LOG_COLOR: always
