name: actionlint
description: Run actionlint and report results by reviewdog
author: Shunsuke Suzuki
inputs:
  github_token:
    required: false
    default: ${{ github.token }}
    description: |
      GitHub Access Token.
      pull-requests:write - Post review comments by reviewdog
      checks:write - Create check runs by reviewdog if the event isn't pull_request
  actionlint_options:
    required: false
    description: |
      actionlint's command line options such as `-ignore`.
runs:
  using: node24
  main: dist/index.js
