---
name: actionlint
on: pull_request
jobs:
  actionlint:
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    permissions:
      contents: read # For actions/checkout
      pull-requests: write # For reviewdog to post review comments
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/actionlint-action@bbb96e7fa8a7dd46b10ae443f05592eb5c406b5b # v0.2.0
        with:
          # dist/index.js isn't committed in this repository. You can remove this.
          ignores: file "dist/index.js" does not exist
