---
name: test
on: pull_request
permissions: {}
jobs:
  status-check:
    runs-on: ubuntu-26.04
    permissions:
      pull-requests: write # For reviewdog
      id-token: write # For Takumi Guard
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - uses: flatt-security/setup-takumi-guard-npm@14f07d0cbc739b42a1b7c70a04c2b84cd1318ddd # v1.4.0
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
      - run: npm ci
      - run: npm t
      - run: npm run lint
      - run: npm run build
      - uses: ./
        with:
          ignores: file "dist/index.js" does not exist
      - uses: ./
        with:
          ignores: file "dist/index.js" does not exist
          shellcheck: ""
          pyflakes: ""
